### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by Michael2008S** [SapienNetwork/Sapien-Presale#1]
```
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0xa5aa5132ae397268d9757512e0aad1164de440a13236de28af05acbfafda6425
  Migrations: 0x35ba5344c70299a01c961032124a2cfd33683d06
Saving successful migration to network...
  ... 0xdaeb6004613f1ca56a6020ff5bc2126a810b91d07f74dd9ea71828a9ab744298
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying Owned...
  ... 0x2063524b9e786e723a927d899cd17f821911f1920885183f2dab206634a57d15
  Owned: 0x3b7deb2dadad9033d74998fc0ce04a14e7312593
Saving successful migration to network...
  Deploying MultiSigWallet...
  ... 0x4fa2c984f7878ee4f5ca0fe8533ba43d02fb539e71c08e4ada21dabc97d75344
Saving artifacts...
  ... 0x1cde054ea74a43d19b3bf444bba63b3cd9f68543665c1664c18d3baebefc5523
  MultiSigWallet: 0xae8f0cc560bdc040e08c5adbcc2b06937412078a
  Deploying SapienToken...
  ... 0x572760321200284358b55a3860e979ddd9127f4f1fa980d4a03b13329ea4d2e9
  SapienToken: 0x90d465ea69aa3bff2df2aafed324f4d32443e810
  Deploying TokenController...
  ... 0xe2c93419b4dde6c7932fba3c7f234e7e3450f53704f2cbaece0802a5faa6bbae
  TokenController: 0xea6f1436edfa91bd8aa5b1fc093b82af0bf159ac
  Deploying SapienCrowdsale...
  ... 0x2f02d1000290532948ea70d99ef0bd865822362ec6a1ad2463fa065731ee7e52
  SapienCrowdsale: 0x770f97c8dd61cc9da0cb97e99e84b7bc2527cc45
  Deploying DynamicCrowdsale...
  ... 0x76fe0bfae9937e8d9afe561276be9708b1f76534e87f14dff23a91e4909d6ad0
  DynamicCrowdsale: 0x62fd3361c3c343abe548c654027b2c53987162d5
  Deploying CrowdsaleStorage...
  ... 0x0f5e263362be5dd6870b808814cfebf0acb45817cd4cbad362ab0ea38dfa9d31
  CrowdsaleStorage: 0xaf6d843e2b02057dd859214ec2c81caac00c31dd
  Deploying SPNStorage...
  ... 0xeceaf49c5cb915b846df6baf24d5178c32acbe93bf0bd3ad152de4b15473d957
  SPNStorage: 0xd2c03a23dabc85aebe6a1da33e176cb82c2f521c
  Deploying SapienStaking...
  ... 0x5949c2c668bb29566f234da8c0d77fe017902f12476b066fec32efbdfeee2045
  SapienStaking: 0xbd79b53cecf0691f503cdcc34c8991cc328c445c
  ... 0x6cd4b9ee127990125f853fa15827808face965e0a069fba89a9c099fb5fdd96d
  ... 0x0717c49fc46e06b17f5a24b4681590c0a0df4fdaf4c8b24c7eecc7ea60df8b68
  ... 0xc9ab50279243f980759a747bf834bc93ae14accc71c2744566677075763417d7
  ... 0xe3318a37b43077eaae14cad9620b4730643d27dfdbc4b6264b9c0317433a80cd
(node:20128) UnhandledPromiseRejectionWarning: Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:25:1)
    at SolidityFunction.validateArgs (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:74:1)
    at SolidityFunction.toPayload (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:90:1)
    at SolidityFunction.sendTransaction (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:163:1)
    at SolidityFunction.execute (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
    at module.exports (/Volumes/RamDisk/Sapien-Presale/migrations/2_deploy_contracts.js:45:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:20128) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20128) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by naure** [comment]
This repository is not up-to-date at the moment.
